#ifndef _GLOBAL_CONSTANTS_H_INCLUDED
#define _GLOBAL_CONSTANTS_H_INCLUDED

#define MAX_TIMER_COUNT 0xFFFF
#define TIMER_PERIOD MAX_TIMER_COUNT/3

#define MAX_ADC_VAL 1023 // Max value of 10 Bit ADC

#endif // _GLOBAL_CONSTANTS_H_INCLUDED