#ifndef _GLOBAL_CONSTANTS_H_INCLUDED
#define _GLOBAL_CONSTANTS_H_INCLUDED

// Built-in LED
#define LED_BUILTIN_PORT GPIOB
#define LED_BUILTIN_PIN  GPIO_PIN_5

// Potentiometer
#define POT_GPIO_PORT GPIOD
#define POT_GPIO_PIN  GPIO_PIN_3
#define POT_ADC_CHANNEL ADC1_CHANNEL_4 // Channel 4 is connected to GPIO PD3 (See STM8CubeMX pinout for STM8S103F3Px)
#define POT_ADC_ADC_SCHMITTTRIG_CHANNEL ADC1_SCHMITTTRIG_CHANNEL4

#define MAX_ADC_VAL 1023 // Max value of 10 Bit ADC

#endif // _GLOBAL_CONSTANTS_H_INCLUDED